### ISSUE TITLE
Problem with colors?

### ISSUE THREAD

**Issue by filipre** [miurahr/pykakasi#120]
**Describe the bug**
When I convert `オレンジ色` I get `おれんじ` and `しょく` but should it not be `いろ` in this context, see [here](http://takoboto.jp/?q=%E3%82%AA%E3%83%AC%E3%83%B3%E3%82%B8%E8%89%B2)? Is there a way to provide more context for the converter?

**To Reproduce**

```python
import pykakasi
kks = pykakasi.kakasi()
text = "オレンジ色"
result = kks.convert(text)
for item in result:
    print("{}: kana '{}', hiragana '{}', romaji: '{}'".format(
        item['orig'], item['kana'], item['hira'], item['hepburn']))
```

**Expected behavior**
see above

**Environment (please complete the following information):**
 - OS: Mac OS X 11.2.3
 - Python `Python 3.6.8 :: Anaconda, Inc.`
 - pykakasi version: `Version: 2.0.6`

**Test data(please attach in the report):**
see code above

**Comment by miurahr** [comment]
It is the  limitation of algorithm KAKASI take from original version.
KAKASI use simple longest match for KANJI **without** back-track after splitting character types.
KAKSI don't analyze detailed 形態素解析(Morphological Analysis）.

'オレンジ色' will be processed   'オレンジ'   + '色'  then '色' is searched from dictionary.

Because KAKASI use only forward match,  '色彩' is matched and converted to 'しきさい'.   '色' is matched 'いろ' and 'しょく'' then take a last match.
To convert 'オレンジ色' to proper result, we need to add word to the dictionary.

When you need more precise analyze and convert, please consider use another library such as CHASEN, Mecab, and janome.

**Comment by miurahr** [comment]
One of weak point of KAKASI algorithm is a case of  combination with KANA+KANJI.
For example, '橙色' will match and convert 'だいだいいろ' 'daidaiiro', because the word begins with KANJI,  but 'オレンジ色' is begin with KANA.

**Comment by filipre** [comment]
Thank you for the detailed explanation! I wonder, could we solve this issue by providing some sort of look-up dictionary before splitting the text into components? How many words are there in Japanese that are KANA+KANJI like オレンジ色? If the list is small, we could take the most common ones and check for them first?

**Comment by miurahr** [comment]
The issue is not a dictionary problem
You can understand the issue to know a forward tracking.

KAKASI has a forward tracking mechanism.
Dictionary has an extension for word. For example,  there are record (1) ``へt 減``, (2) ``へr 減`` and (3) ``げん 減``.
This will match  ``減った``  and ``減って`` by (1)  and ``減る`` ``減らない`` by  (2) then produce ``へ(he)``, otherwise match to (3) and produce ``げん(gen)``
This is forward tracking. KAKASI see the next KANA of KANJI then change its corresponding output.

In the situation of the color name,  we may need to realize a back tracking.  When character pointer to reach ``色`` and prior word is known color name,  a dictionary may reverse index, such as ``ジンレオ`` and match it then use ``いろ(iro)`` is taken.

**Comment by filipre** [comment]
I see, makes sense. I do understand why we would need backtracking now. Thanks again!

I was just thinking, as a very dirty hack, can't we just have a preprocessing step (before the forward tracking) that scans the whole text for certain kana + kanji combinations, before doing the actual parsing? Then we could print a warning to tell the user to be cautious about used terms. For example, whenever the phrase `オレンジ色` appears in the text, we would already know that there is a kana+kanji word before doing any parsing and splitting whatsoever. But I don't know if it would be even worth the effort and it may introduce new problems.

In the end, it depends where you want to take this project. I like this project because it is 100% python (is it not?) and thus does not need third-party programs such as Mecab.

**Comment by miurahr** [comment]
I think back tracking is not so difficult. After version 2.0, we have a structured result in `_result` variable of kakasi class that is list of dictionary.
When calling conversion of KANJI-KANA function, we can also pass a previous word 'kana'. I'd like to try with simple mod.

**Comment by miurahr** [comment]
#132 try to implement the feature.
It convert "オレンジ色" to "オレンジ" "いろ" as @filipre described.
It is very experimental now...

**Comment by miurahr** [comment]
Current dev branch only have a  "色"  context data in the dictionary.
It should be updated for many words before release.
